version: '4.34'

services:
  php:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    container_name: symfony_php
    volumes:
      - .:/var/www/html
      - ./vendor:/var/www/html/vendor
    ports:
      - "9000:9000"

  nginx:
    image: nginx:alpine
    container_name: symfony_nginx
    volumes:
      - .:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php

  postgres:
    image: postgres:alpine
    container_name: symfony_postgres
    environment:
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
      POSTGRES_DB: symfony
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
